name=NahuCore
version=0.1.0
author=Nahu Avrilero
maintainer=Nahu Avrilero
sentence=Biblioteca modular para reducir código repetitivo en proyectos Arduino con ESP32.
paragraph=Proporciona componentes reutilizables para conectividad, configuración, MQTT y otras funciones frecuentes en proyectos IoT. Actualmente incluye NahuWifi.
category=Communication
url=https://github.com/nahuavrilero/nahuCore
architectures=esp32
includes=nahuWifi.h